SchoolManagementSystem/SchoolManagementSystem/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using SchoolManagementSystem.Models;
using SchoolManagementSystem.ViewModel;

namespace SchoolManagementSystem.Controllers
{
    public class AuthController : Controller
    {

        private readonly IConfiguration config;
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;

        public AuthController(IConfiguration config,
            UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            this.config = config;
            this.userManager = userManager;
            this.signInManager = signInManager;

        }

        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginVm login)
        {
            try
            {
                var user = await userManager.FindByNameAsync(login.UserName);

                if (user != null)
                {
                    var result = await signInManager.CheckPasswordSignInAsync(user, login.Password, false);
                    if (result.Succeeded)
                    {
                        var appUser = userManager.Users.FirstOrDefault(x => x.NormalizedUserName == login.UserName.ToUpper());
                        string token =await GenerateTokenAsync(appUser);
                        if (token != null)
                        {
                            HttpContext.Session.SetString("JWToken", token);
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }

                ViewBag.ErrorMsg = "Incorrect UserId or Password";
                return View(login);
            }
            catch (Exception)
            {

                return RedirectToAction("Unknown", "Error");
            }


        }

        [Authorize(Roles = "Admin")]
        public IActionResult ChangeAdminPassword()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> ChangeAdminPassword(ChangePasswordViewModel model)
        {
            try
            {

                if (!model.NewPassword.Equals(model.ConfirmPassword))
                {
                    ViewBag.ErrorMsg = "New Passoword and Confirm Password Doesn't Match";
                    return View(model);
                }

                if (model.NewPassword.Equals(model.CurrentPassword))
                {
                    ViewBag.ErrorMsg = "Current Password and New Password are Same";
                    return View(model);
                }

                if (model.NewPassword.Length < 4)
                {
                    ViewBag.ErrorMsg = "Minimum 4 Digid Required";
                    return View(model);
                }

                var user = await userManager.FindByNameAsync("Admin");
                var result = await signInManager.CheckPasswordSignInAsync(user, model.CurrentPassword, false);

                if (result.Succeeded)
                {
                    var isChange = await userManager.ChangePasswordAsync(user, model.CurrentPassword, model.NewPassword);
                    if (isChange.Succeeded)
                    {
                        return RedirectToAction(nameof(Logout));
                    }
                }

                ViewBag.ErrorMsg = "Incorrect Current Password";
                return View(model);


            }
            catch (Exception)
            {

                return Unauthorized();
            }


        }

        private async Task<string> GenerateTokenAsync(AppUser user)
        {
            


            //Creating Jwt Token
            var claims = new List<Claim>()
            {
                new Claim(ClaimTypes.NameIdentifier,user.Id.ToString()),
                new Claim(ClaimTypes.Name,user.UserName),
                new Claim(ClaimTypes.Surname,user.FullName),
            };


            //Adding token in the token
            var roles = await userManager.GetRolesAsync(user);
            foreach (var role in roles)
            {
                claims.Add(new Claim(ClaimTypes.Role, role));
            }

            var key  = Encoding.UTF8.GetBytes(config.GetSection("Application:Token").Value);
            //Generate Token for user 
            var JWToken = new JwtSecurityToken(
                issuer: config.GetSection("Application:DomainName").Value,
                audience: config.GetSection("Application:DomainName").Value,
                claims: claims,
                notBefore: new DateTimeOffset(DateTime.Now).DateTime,
                expires: new DateTimeOffset(DateTime.Now.AddDays(7)).DateTime,
                //Using HS256 Algorithm to encrypt Token  
                signingCredentials: new SigningCredentials
                (new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
            );
            var token = new JwtSecurityTokenHandler().WriteToken(JWToken);
            return token;

        }


        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction(nameof(Login));
        }
    }
}

SchoolManagementSystem/SchoolManagementSystem/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolManagementSystem.Models;

namespace SchoolManagementSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ModuleController : Controller
    {
        private readonly SchoolDbContext _context;

        public ModuleController(SchoolDbContext context)
        {
            _context = context;
        }

        // GET: Module
        public async Task<IActionResult> Index()
        {
            return View(await _context.Modules.Include(m=>m.Programme).ToListAsync());
        }

        // GET: Module/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules
                .FirstOrDefaultAsync(m => m.ModuleID == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // GET: Module/Create
        public IActionResult Create()
        {
            try
            {
                ViewBag.ProgrammeList = _context.Programmes.ToList();
                ViewBag.ModuleID = GetModuleId();
                return View();
            }
            catch (Exception)
            {

                return RedirectToAction("Unknown", "Error");
            }

            
        }

        // POST: Module/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Module @module)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(@module);
                    await _context.SaveChangesAsync();
                    ViewBag.SuccessMsg = "Module Created Successfully";

                    ViewBag.ProgrammeList = _context.Programmes.ToList();
                    ViewBag.ModuleID = GetModuleId();
                    ModelState.Clear();
                    return View();
                }
                return View(@module);
            }
            catch (Exception)
            {

                return RedirectToAction("Unknown", "Error");
            }
            
        }


        private string GetModuleId()
        {
            string moduleID = "";
            while (_context.Modules.Any(m => m.ModuleID == moduleID) || moduleID == "")
            {
                Random r = new Random();
                moduleID = "M" + r.Next(100_00, 999_99).ToString();
            }
            return moduleID;
        }

        // GET: Module/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _context.Modules.FindAsync(id);
            ViewBag.ProgrammeList = _context.Programmes.ToList();
            //ViewBag.ProgrammeID= new SelectList(_context.Programmes, "Id", "Name", module.ProgrammeID);
            if (@module == null)
            {
                return NotFound();
            }
            return View(@module);
        }

        // POST: Module/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ModuleID,ModuleName,ModuleDescription,ModuleCredits")] Module @module)
        {
            if (id != @module.ModuleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@module);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(@module.ModuleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Module/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            var @module = await _context.Modules
                .FirstOrDefaultAsync(m => m.ModuleID == id);
            if (@module == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            return View(@module);
        }

        // POST: Module/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var @module = await _context.Modules.FindAsync(id);
                _context.Modules.Remove(@module);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                string errorMsg = "Module cannot be deleted. Because It is used in other Entity (Ex. Student, Assessment, AssessmentResult). If you really want to Delete, Please remove those entity first which use this Module and Try Again";
                return RedirectToAction("Delete", "Error", new { errorMsg = errorMsg });
            }


        }

        private bool ModuleExists(string id)
        {
            return _context.Modules.Any(e => e.ModuleID == id);
        }
    }
}

SchoolManagementSystem/SchoolManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolManagementSystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-info" >

            <div class="container-fluid">
                <a class="btn font-weight-bold" style="color:white" asp-area="" asp-controller="Home" asp-action="Index">School Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="btn btn-info" asp-area="" asp-controller="Home" asp-action="Index" >Home</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="btn btn-info dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                                    Programme
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Programme" asp-action="Create">Create</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Programme" asp-action="index">Pragramme List</a>
                                </div>
                            </li>
                        }



                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="btn btn-info dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                                    Module
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Module" asp-action="Create">Create</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Module" asp-action="index">Module List</a>
                                </div>
                            </li>
                        }



                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="btn btn-info dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                                    Assessment
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Assessments" asp-action="Create">Create</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Assessments" asp-action="index">Assessment List</a>
                                </div>
                            </li>
                        }



                        @{
                            if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="btn btn-info dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                                        Assessment Result
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="AssessmentResults" asp-route-id="@null" asp-action="Submit">Submit</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="AssessmentResults" asp-action="ShowAll">Assessment Result List</a>
                                    </div>
                                </li>
                            }
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="btn btn-info dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                                    Register User
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Student" asp-action="Register">Student</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Teacher" asp-action="Register">Teacher</a>
                                </div>
                            </li>
                        }


                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="btn btn-info dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                                    User List
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Student" asp-action="ShowAll">Student List</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher List</a>
                                </div>
                            </li>
                        }

                        @if (User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                <a class="btn btn-info" asp-area="" asp-controller="Student" asp-action="ShowResult" asp-route-id="@User.Identity.Name">See Your Result</a>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav ml-auto">



                        @if (User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                <a class="btn btn-info" asp-area="" asp-controller="Student" asp-action="Details" asp-route-id="@User.Identity.Name">Profile</a>
                            </li>
                        }

                        @if (User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="btn btn-info" asp-area="" asp-controller="Teacher" asp-action="Details" asp-route-id="@User.Identity.Name">Profile</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="btn btn-info" asp-area="" asp-controller="Auth" asp-action="ChangeAdminPassword">Change Password</a>
                            </li>
                        }

                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item dropdown">
                                    <a class="btn btn-info dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                                        
                                        @{
                                            var list=  User.Claims.ToList();
                                            string surname = list[2].Value;

                                        }

                                        Welcome @surname
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                                    </div>
                                </li>
                            }

                        }


                    </ul>
                </div>
            </div>

        </nav>

        

    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            <br />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SchoolManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>